/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 30/04/2014 01:41:21 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Anonymouscomplaint generated by hbm2java
 */
public class Anonymouscomplaint implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idanonymouscomplaint;
	private String pecomment;
	private Date dateserver;
	private Boolean notificationcomplianceofficer;

	public Anonymouscomplaint() {
	}

	public Anonymouscomplaint(long idanonymouscomplaint) {
		this.idanonymouscomplaint = idanonymouscomplaint;
	}

	public Anonymouscomplaint(long idanonymouscomplaint, String pecomment,
			Date dateserver, Boolean notificationcomplianceofficer) {
		this.idanonymouscomplaint = idanonymouscomplaint;
		this.pecomment = pecomment;
		this.dateserver = dateserver;
		this.notificationcomplianceofficer = notificationcomplianceofficer;
	}

	public long getIdanonymouscomplaint() {
		return this.idanonymouscomplaint;
	}

	public void setIdanonymouscomplaint(long idanonymouscomplaint) {
		this.idanonymouscomplaint = idanonymouscomplaint;
	}

	public String getPecomment() {
		return this.pecomment;
	}

	public void setPecomment(String pecomment) {
		this.pecomment = pecomment;
	}

	public Date getDateserver() {
		return this.dateserver;
	}

	public void setDateserver(Date dateserver) {
		this.dateserver = dateserver;
	}

	public Boolean getNotificationcomplianceofficer() {
		return this.notificationcomplianceofficer;
	}

	public void setNotificationcomplianceofficer(
			Boolean notificationcomplianceofficer) {
		this.notificationcomplianceofficer = notificationcomplianceofficer;
	}

}
