/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Blacklist generated by hbm2java
 */
public class Blacklist implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idblacklist;
	private String name;
	private String secondname;
	private String surname;
	private Date datebirth;
	private String gender;
	private Long celnumber;
	private String nationality;

	public Blacklist() {
	}

	public Blacklist(long idblacklist, String name, String secondname,
			String surname) {
		this.idblacklist = idblacklist;
		this.name = name;
		this.secondname = secondname;
		this.surname = surname;
	}

	public Blacklist(long idblacklist, String name, String secondname,
			String surname, Date datebirth, String gender, Long celnumber,
			String nationality) {
		this.idblacklist = idblacklist;
		this.name = name;
		this.secondname = secondname;
		this.surname = surname;
		this.datebirth = datebirth;
		this.gender = gender;
		this.celnumber = celnumber;
		this.nationality = nationality;
	}

	public long getIdblacklist() {
		return this.idblacklist;
	}

	public void setIdblacklist(long idblacklist) {
		this.idblacklist = idblacklist;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSecondname() {
		return this.secondname;
	}

	public void setSecondname(String secondname) {
		this.secondname = secondname;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Date getDatebirth() {
		return this.datebirth;
	}

	public void setDatebirth(Date datebirth) {
		this.datebirth = datebirth;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Long getCelnumber() {
		return this.celnumber;
	}

	public void setCelnumber(Long celnumber) {
		this.celnumber = celnumber;
	}

	public String getNationality() {
		return nationality;
	}

	public void setNationality(String nationality) {
		this.nationality = nationality;
	}

}
