/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

/**
 * Customerregistration generated by hbm2java
 */
public class Customerregistration implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idcustomerregistration;
	private Customer customer;
	private Logcall logcall;

	public Customerregistration() {
	}

	public Customerregistration(long idcustomerregistration) {
		this.idcustomerregistration = idcustomerregistration;
	}

	public Customerregistration(long idcustomerregistration, Customer customer,
			Logcall logcall) {
		this.idcustomerregistration = idcustomerregistration;
		this.customer = customer;
		this.logcall = logcall;
	}

	public long getIdcustomerregistration() {
		return this.idcustomerregistration;
	}

	public void setIdcustomerregistration(long idcustomerregistration) {
		this.idcustomerregistration = idcustomerregistration;
	}
	
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Logcall getLogcall() {
		return this.logcall;
	}

	public void setLogcall(Logcall logcall) {
		this.logcall = logcall;
	}

}
