/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idcustomer;
	private Domicilios domicilios;
	private Customerstate customerstate;
	private Customerriskiness customerriskiness;
	private String name;
	private String secondname;
	private String surname;
	private Date datebirth;
	private String gender;
	private long numcrenelector;
	private String numpassaporte;
	private String cartillamilitar;
	private String occupation;
	private String company;
	private Long celnumber;
	private Long telnumber;
	private String email;
	private String pecomment;
	private Date lastsession;
	private Byte failedattempscounter;
	private String username;
	private Date datemodified;
	private short isactive;
	private boolean disabled;
	private String statusCall;
	private Set<Customerchangehistory> customerchangehistories = new HashSet<Customerchangehistory>(
			0);
	private Set<Customerregistration> customerregistrations = new HashSet<Customerregistration>(
			0);

	public Customer() {
	}

	public Customer(long idcustomer, Customerstate customerstate,
			Customerriskiness customerriskiness, long numcrenelector,
			Date lastsession, String username, Date datemodified, short isactive) {
		this.idcustomer = idcustomer;
		this.customerstate = customerstate;
		this.customerriskiness = customerriskiness;
		this.numcrenelector = numcrenelector;
		this.lastsession = lastsession;
		this.username = username;
		this.datemodified = datemodified;
		this.isactive = isactive;
	}

	public Customer(long idcustomer, Domicilios domicilios,
			Customerstate customerstate, Customerriskiness customerriskiness,
			String name, String secondname, String surname, Date datebirth,
			String gender, long numcrenelector, String numpassaporte,
			String cartillamilitar, String occupation, String company,
			Long celnumber, Long telnumber, String email, String pecomment,
			Date lastsession, Byte failedattempscounter, String username,
			Date datemodified, short isactive,
			Set<Customerchangehistory> customerchangehistories,
			Set<Customerregistration> customerregistrations) {
		this.idcustomer = idcustomer;
		this.domicilios = domicilios;
		this.customerstate = customerstate;
		this.customerriskiness = customerriskiness;
		this.name = name;
		this.secondname = secondname;
		this.surname = surname;
		this.datebirth = datebirth;
		this.gender = gender;
		this.numcrenelector = numcrenelector;
		this.numpassaporte = numpassaporte;
		this.cartillamilitar = cartillamilitar;
		this.occupation = occupation;
		this.company = company;
		this.celnumber = celnumber;
		this.telnumber = telnumber;
		this.email = email;
		this.pecomment = pecomment;
		this.lastsession = lastsession;
		this.failedattempscounter = failedattempscounter;
		this.username = username;
		this.datemodified = datemodified;
		this.isactive = isactive;
		this.customerchangehistories = customerchangehistories;
		this.customerregistrations = customerregistrations;
	}

	public long getIdcustomer() {
		return this.idcustomer;
	}

	public void setIdcustomer(long idcustomer) {
		this.idcustomer = idcustomer;
	}

	public Domicilios getDomicilios() {
		return this.domicilios;
	}

	public void setDomicilios(Domicilios domicilios) {
		this.domicilios = domicilios;
	}

	public Customerstate getCustomerstate() {
		return this.customerstate;
	}

	public void setCustomerstate(Customerstate customerstate) {
		this.customerstate = customerstate;
	}

	public Customerriskiness getCustomerriskiness() {
		return this.customerriskiness;
	}

	public void setCustomerriskiness(Customerriskiness customerriskiness) {
		this.customerriskiness = customerriskiness;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSecondname() {
		return this.secondname;
	}

	public void setSecondname(String secondname) {
		this.secondname = secondname;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public Date getDatebirth() {
		return this.datebirth;
	}

	public void setDatebirth(Date datebirth) {
		this.datebirth = datebirth;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public long getNumcrenelector() {
		return this.numcrenelector;
	}

	public void setNumcrenelector(long numcrenelector) {
		this.numcrenelector = numcrenelector;
	}

	public String getNumpassaporte() {
		return this.numpassaporte;
	}

	public void setNumpassaporte(String numpassaporte) {
		this.numpassaporte = numpassaporte;
	}

	public String getCartillamilitar() {
		return this.cartillamilitar;
	}

	public void setCartillamilitar(String cartillamilitar) {
		this.cartillamilitar = cartillamilitar;
	}

	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(String occupation) {
		this.occupation = occupation;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public Long getCelnumber() {
		return this.celnumber;
	}

	public void setCelnumber(Long celnumber) {
		this.celnumber = celnumber;
	}

	public Long getTelnumber() {
		return this.telnumber;
	}

	public void setTelnumber(Long telnumber) {
		this.telnumber = telnumber;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPecomment() {
		return this.pecomment;
	}

	public void setPecomment(String pecomment) {
		this.pecomment = pecomment;
	}

	public Date getLastsession() {
		return this.lastsession;
	}

	public void setLastsession(Date lastsession) {
		this.lastsession = lastsession;
	}

	public Byte getFailedattempscounter() {
		return this.failedattempscounter;
	}

	public void setFailedattempscounter(Byte failedattempscounter) {
		this.failedattempscounter = failedattempscounter;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Date getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Date datemodified) {
		this.datemodified = datemodified;
	}

	public short getIsactive() {
		return this.isactive;
	}

	public void setIsactive(short isactive) {
		this.isactive = isactive;
	}

	public Set<Customerchangehistory> getCustomerchangehistories() {
		return this.customerchangehistories;
	}

	public void setCustomerchangehistories(
			Set<Customerchangehistory> customerchangehistories) {
		this.customerchangehistories = customerchangehistories;
	}

	public Set<Customerregistration> getCustomerregistrations() {
		return this.customerregistrations;
	}

	public void setCustomerregistrations(
			Set<Customerregistration> customerregistrations) {
		this.customerregistrations = customerregistrations;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + (int) (idcustomer ^ (idcustomer >>> 32));
		return result;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Customer other = (Customer) obj;
		if (idcustomer != other.idcustomer)
			return false;
		return true;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	@Override
	public String toString() {
		return "Customer [idcustomer=" + idcustomer + ", domicilios="
				+ domicilios + ", name=" + name + ", secondname=" + secondname
				+ ", surname=" + surname + ", datebirth=" + datebirth
				+ ", gender=" + gender + ", numcrenelector=" + numcrenelector
				+ ", numpassaporte=" + numpassaporte + ", cartillamilitar="
				+ cartillamilitar + ", occupation=" + occupation + ", company="
				+ company + ", celnumber=" + celnumber + ", telnumber="
				+ telnumber + ", email=" + email + ", pecomment=" + pecomment
				+ ", lastsession=" + lastsession + ", failedattempscounter="
				+ failedattempscounter + ", username=" + username
				+ ", datemodified=" + datemodified + ", isactive=" + isactive
				+ "]";
	}

	/**
	 * @return the disabled
	 */
	public boolean isDisabled() {
		return disabled;
	}

	/**
	 * @param disabled the disabled to set
	 */
	public void setDisabled(boolean disabled) {
		this.disabled = disabled;
	}

	/**
	 * @return the statusCall
	 */
	public String getStatusCall() {
		return statusCall;
	}

	/**
	 * @param statusCall the statusCall to set
	 */
	public void setStatusCall(String statusCall) {
		this.statusCall = statusCall;
	}
	

}
