/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Customerchangehistory generated by hbm2java
 */
public class Customerchangehistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idcustomerchangehistory;
	private Customer customer;
	private Serializable dateserver;
	private String reason;

	public Customerchangehistory() {
	}

	public Customerchangehistory(long idcustomerchangehistory,
			Customer customer, Serializable dateserver) {
		this.idcustomerchangehistory = idcustomerchangehistory;
		this.customer = customer;
		this.dateserver = dateserver;
	}

	public Customerchangehistory(long idcustomerchangehistory,
			Customer customer, Serializable dateserver, String reason) {
		this.idcustomerchangehistory = idcustomerchangehistory;
		this.customer = customer;
		this.dateserver = dateserver;
		this.reason = reason;
	}

	public long getIdcustomerchangehistory() {
		return this.idcustomerchangehistory;
	}

	public void setIdcustomerchangehistory(long idcustomerchangehistory) {
		this.idcustomerchangehistory = idcustomerchangehistory;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Serializable getDateserver() {
		return this.dateserver;
	}

	public void setDateserver(Serializable dateserver) {
		this.dateserver = dateserver;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
