/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Customerstate generated by hbm2java
 */
public class Customerstate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idcustomerstate;
	private String state;
	private String description;
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Customerstate() {
	}

	public Customerstate(int idcustomerstate, String state, String description) {
		this.idcustomerstate = idcustomerstate;
		this.state = state;
		this.description = description;
	}

	public Customerstate(int idcustomerstate, String state, String description,
			Set<Customer> customers) {
		this.idcustomerstate = idcustomerstate;
		this.state = state;
		this.description = description;
		this.customers = customers;
	}

	public int getIdcustomerstate() {
		return this.idcustomerstate;
	}

	public void setIdcustomerstate(int idcustomerstate) {
		this.idcustomerstate = idcustomerstate;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
