/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Domicilios generated by hbm2java
 */
public class Domicilios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idDomicilio;
	private Colonias colonias;
	private String calleYNum;
	private String usuarioBd;
	private Date fechaModificacion;
	private String comentarios;
	private Set<Currencycode> currencycodes = new HashSet<Currencycode>(0);
	private Set<Workinggroup> workinggroups = new HashSet<Workinggroup>(0);
	private Set<Pecompany> pecompanies = new HashSet<Pecompany>(0);
	private Set<Pebranch> pebranches = new HashSet<Pebranch>(0);
	private Set<Partner> partners = new HashSet<Partner>(0);
	private Set<Employee> employees = new HashSet<Employee>(0);
	private Set<Customer> customers = new HashSet<Customer>(0);

	public Domicilios() {
	}

	public Domicilios(long idDomicilio, String calleYNum, String usuarioBd,
			Date fechaModificacion) {
		this.idDomicilio = idDomicilio;
		this.calleYNum = calleYNum;
		this.usuarioBd = usuarioBd;
		this.fechaModificacion = fechaModificacion;
	}

	public Domicilios(long idDomicilio, Colonias colonias, String calleYNum,
			String usuarioBd, Date fechaModificacion, String comentarios,
			Set<Currencycode> currencycodes, Set<Workinggroup> workinggroups,
			Set<Pecompany> pecompanies, Set<Pebranch> pebranches,
			Set<Partner> partners, Set<Employee> employees,
			Set<Customer> customers) {
		this.idDomicilio = idDomicilio;
		this.colonias = colonias;
		this.calleYNum = calleYNum;
		this.usuarioBd = usuarioBd;
		this.fechaModificacion = fechaModificacion;
		this.comentarios = comentarios;
		this.currencycodes = currencycodes;
		this.workinggroups = workinggroups;
		this.pecompanies = pecompanies;
		this.pebranches = pebranches;
		this.partners = partners;
		this.employees = employees;
		this.customers = customers;
	}

	public long getIdDomicilio() {
		return this.idDomicilio;
	}

	public void setIdDomicilio(long idDomicilio) {
		this.idDomicilio = idDomicilio;
	}

	public Colonias getColonias() {
		return this.colonias;
	}

	public void setColonias(Colonias colonias) {
		this.colonias = colonias;
	}

	public String getCalleYNum() {
		return this.calleYNum;
	}

	public void setCalleYNum(String calleYNum) {
		this.calleYNum = calleYNum;
	}

	public String getUsuarioBd() {
		return this.usuarioBd;
	}

	public void setUsuarioBd(String usuarioBd) {
		this.usuarioBd = usuarioBd;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public String getComentarios() {
		return this.comentarios;
	}

	public void setComentarios(String comentarios) {
		this.comentarios = comentarios;
	}

	public Set<Currencycode> getCurrencycodes() {
		return this.currencycodes;
	}

	public void setCurrencycodes(Set<Currencycode> currencycodes) {
		this.currencycodes = currencycodes;
	}

	public Set<Workinggroup> getWorkinggroups() {
		return this.workinggroups;
	}

	public void setWorkinggroups(Set<Workinggroup> workinggroups) {
		this.workinggroups = workinggroups;
	}

	public Set<Pecompany> getPecompanies() {
		return this.pecompanies;
	}

	public void setPecompanies(Set<Pecompany> pecompanies) {
		this.pecompanies = pecompanies;
	}

	public Set<Pebranch> getPebranches() {
		return this.pebranches;
	}

	public void setPebranches(Set<Pebranch> pebranches) {
		this.pebranches = pebranches;
	}

	public Set<Partner> getPartners() {
		return this.partners;
	}

	public void setPartners(Set<Partner> partners) {
		this.partners = partners;
	}

	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

	public Set<Customer> getCustomers() {
		return this.customers;
	}

	public void setCustomers(Set<Customer> customers) {
		this.customers = customers;
	}

}
