package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Employeechangehistory generated by hbm2java
 */
public class Employeechangehistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idemployeechangehistory;
	private Employee employee;
	private Serializable datemodified;
	private String reason;

	public Employeechangehistory() {
	}

	public Employeechangehistory(long idemployeechangehistory,
			Employee employee, Serializable datemodified) {
		this.idemployeechangehistory = idemployeechangehistory;
		this.employee = employee;
		this.datemodified = datemodified;
	}

	public Employeechangehistory(long idemployeechangehistory,
			Employee employee, Serializable datemodified, String reason) {
		this.idemployeechangehistory = idemployeechangehistory;
		this.employee = employee;
		this.datemodified = datemodified;
		this.reason = reason;
	}

	public long getIdemployeechangehistory() {
		return this.idemployeechangehistory;
	}

	public void setIdemployeechangehistory(long idemployeechangehistory) {
		this.idemployeechangehistory = idemployeechangehistory;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Serializable getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Serializable datemodified) {
		this.datemodified = datemodified;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
