/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Blob;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idemployee;
	private Domicilios domicilios;
	private Workinggroup workinggroup;
	private String immediateboss;
	private String name;
	private String secondname;
	private String surname;
	private String gender;
	private Date datebirthay;
	private Long numcredelector;
	private String numpasaporte;
	private String cartillamilitar;
	private Long telephone;
	private Integer ext;
	private Long celnumber1;
	private Long celnumber2;
	private String emailjob;
	private String emailpersonal;
	private Blob cvpdf;
	private Date dateadmission;
	private Date datedeparture;
	private BigDecimal salary;
	private Serializable datemodified;
	private String username;
	private boolean isactivied;
	private Set<Project> projects = new HashSet<Project>(0);
	private Set<Logbookofactivities> logbookofactivitieses = new HashSet<Logbookofactivities>(
			0);
	private Set<Employeechangehistory> employeechangehistories = new HashSet<Employeechangehistory>(
			0);

	public Employee() {
	}

	public Employee(long idemployee, Workinggroup workinggroup,
			String immediateboss, String name, String secondname,
			String surname, String gender, Date datebirthay, String emailjob,
			Blob cvpdf, Date dateadmission, Date datedeparture,
			BigDecimal salary, Serializable datemodified, String username,
			boolean isactivied) {
		this.idemployee = idemployee;
		this.workinggroup = workinggroup;
		this.immediateboss = immediateboss;
		this.name = name;
		this.secondname = secondname;
		this.surname = surname;
		this.gender = gender;
		this.datebirthay = datebirthay;
		this.emailjob = emailjob;
		this.cvpdf = cvpdf;
		this.dateadmission = dateadmission;
		this.datedeparture = datedeparture;
		this.salary = salary;
		this.datemodified = datemodified;
		this.username = username;
		this.isactivied = isactivied;
	}

	public Employee(long idemployee, Domicilios domicilios,
			Workinggroup workinggroup, String immediateboss, String name,
			String secondname, String surname, String gender, Date datebirthay,
			Long numcredelector, String numpasaporte, String cartillamilitar,
			Long telephone, Integer ext, Long celnumber1, Long celnumber2,
			String emailjob, String emailpersonal, Blob cvpdf,
			Date dateadmission, Date datedeparture, BigDecimal salary,
			Serializable datemodified, String username, boolean isactivied,
			Set<Project> projects,
			Set<Logbookofactivities> logbookofactivitieses,
			Set<Employeechangehistory> employeechangehistories) {
		this.idemployee = idemployee;
		this.domicilios = domicilios;
		this.workinggroup = workinggroup;
		this.immediateboss = immediateboss;
		this.name = name;
		this.secondname = secondname;
		this.surname = surname;
		this.gender = gender;
		this.datebirthay = datebirthay;
		this.numcredelector = numcredelector;
		this.numpasaporte = numpasaporte;
		this.cartillamilitar = cartillamilitar;
		this.telephone = telephone;
		this.ext = ext;
		this.celnumber1 = celnumber1;
		this.celnumber2 = celnumber2;
		this.emailjob = emailjob;
		this.emailpersonal = emailpersonal;
		this.cvpdf = cvpdf;
		this.dateadmission = dateadmission;
		this.datedeparture = datedeparture;
		this.salary = salary;
		this.datemodified = datemodified;
		this.username = username;
		this.isactivied = isactivied;
		this.projects = projects;
		this.logbookofactivitieses = logbookofactivitieses;
		this.employeechangehistories = employeechangehistories;
	}

	public long getIdemployee() {
		return this.idemployee;
	}

	public void setIdemployee(long idemployee) {
		this.idemployee = idemployee;
	}

	public Domicilios getDomicilios() {
		return this.domicilios;
	}

	public void setDomicilios(Domicilios domicilios) {
		this.domicilios = domicilios;
	}

	public Workinggroup getWorkinggroup() {
		return this.workinggroup;
	}

	public void setWorkinggroup(Workinggroup workinggroup) {
		this.workinggroup = workinggroup;
	}

	public String getImmediateboss() {
		return this.immediateboss;
	}

	public void setImmediateboss(String immediateboss) {
		this.immediateboss = immediateboss;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSecondname() {
		return this.secondname;
	}

	public void setSecondname(String secondname) {
		this.secondname = secondname;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public Date getDatebirthay() {
		return this.datebirthay;
	}

	public void setDatebirthay(Date datebirthay) {
		this.datebirthay = datebirthay;
	}

	public Long getNumcredelector() {
		return this.numcredelector;
	}

	public void setNumcredelector(Long numcredelector) {
		this.numcredelector = numcredelector;
	}

	public String getNumpasaporte() {
		return this.numpasaporte;
	}

	public void setNumpasaporte(String numpasaporte) {
		this.numpasaporte = numpasaporte;
	}

	public String getCartillamilitar() {
		return this.cartillamilitar;
	}

	public void setCartillamilitar(String cartillamilitar) {
		this.cartillamilitar = cartillamilitar;
	}

	public Long getTelephone() {
		return this.telephone;
	}

	public void setTelephone(Long telephone) {
		this.telephone = telephone;
	}

	public Integer getExt() {
		return this.ext;
	}

	public void setExt(Integer ext) {
		this.ext = ext;
	}

	public Long getCelnumber1() {
		return this.celnumber1;
	}

	public void setCelnumber1(Long celnumber1) {
		this.celnumber1 = celnumber1;
	}

	public Long getCelnumber2() {
		return this.celnumber2;
	}

	public void setCelnumber2(Long celnumber2) {
		this.celnumber2 = celnumber2;
	}

	public String getEmailjob() {
		return this.emailjob;
	}

	public void setEmailjob(String emailjob) {
		this.emailjob = emailjob;
	}

	public String getEmailpersonal() {
		return this.emailpersonal;
	}

	public void setEmailpersonal(String emailpersonal) {
		this.emailpersonal = emailpersonal;
	}

	public Blob getCvpdf() {
		return this.cvpdf;
	}

	public void setCvpdf(Blob cvpdf) {
		this.cvpdf = cvpdf;
	}

	public Date getDateadmission() {
		return this.dateadmission;
	}

	public void setDateadmission(Date dateadmission) {
		this.dateadmission = dateadmission;
	}

	public Date getDatedeparture() {
		return this.datedeparture;
	}

	public void setDatedeparture(Date datedeparture) {
		this.datedeparture = datedeparture;
	}

	public BigDecimal getSalary() {
		return this.salary;
	}

	public void setSalary(BigDecimal salary) {
		this.salary = salary;
	}

	public Serializable getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Serializable datemodified) {
		this.datemodified = datemodified;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean isIsactivied() {
		return this.isactivied;
	}

	public void setIsactivied(boolean isactivied) {
		this.isactivied = isactivied;
	}

	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

	public Set<Logbookofactivities> getLogbookofactivitieses() {
		return this.logbookofactivitieses;
	}

	public void setLogbookofactivitieses(
			Set<Logbookofactivities> logbookofactivitieses) {
		this.logbookofactivitieses = logbookofactivitieses;
	}

	public Set<Employeechangehistory> getEmployeechangehistories() {
		return this.employeechangehistories;
	}

	public void setEmployeechangehistories(
			Set<Employeechangehistory> employeechangehistories) {
		this.employeechangehistories = employeechangehistories;
	}

}
