/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Estados generated by hbm2java
 */
public class Estados implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private short idEstado;
	private Paises paises;
	private String nombreEstado;
	private Set<Municipios> municipioses = new HashSet<Municipios>(0);

	public Estados() {
	}

	public Estados(short idEstado, Paises paises, String nombreEstado) {
		this.idEstado = idEstado;
		this.paises = paises;
		this.nombreEstado = nombreEstado;
	}

	public Estados(short idEstado, Paises paises, String nombreEstado,
			Set<Municipios> municipioses) {
		this.idEstado = idEstado;
		this.paises = paises;
		this.nombreEstado = nombreEstado;
		this.municipioses = municipioses;
	}

	public short getIdEstado() {
		return this.idEstado;
	}

	public void setIdEstado(short idEstado) {
		this.idEstado = idEstado;
	}

	public Paises getPaises() {
		return this.paises;
	}

	public void setPaises(Paises paises) {
		this.paises = paises;
	}

	public String getNombreEstado() {
		return this.nombreEstado;
	}

	public void setNombreEstado(String nombreEstado) {
		this.nombreEstado = nombreEstado;
	}

	public Set<Municipios> getMunicipioses() {
		return this.municipioses;
	}

	public void setMunicipioses(Set<Municipios> municipioses) {
		this.municipioses = municipioses;
	}

}
