/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Historylogcall generated by hbm2java
 */
public class Historylogcall implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idhistorylogcall;
	private Logcall logcall;
	private Date dateserver;
	private long idstatecall;
	private String attempt;
	private String username;

	public Historylogcall() {
	}

	public Historylogcall(long idhistorylogcall, Logcall logcall,
			Date dateserver, long idstatecall, String username) {
		this.idhistorylogcall = idhistorylogcall;
		this.logcall = logcall;
		this.dateserver = dateserver;
		this.idstatecall = idstatecall;
		this.username = username;
	}

	public Historylogcall(long idhistorylogcall, Logcall logcall,
			Date dateserver, long idstatecall, String attempt, String username) {
		this.idhistorylogcall = idhistorylogcall;
		this.logcall = logcall;
		this.dateserver = dateserver;
		this.idstatecall = idstatecall;
		this.attempt = attempt;
		this.username = username;
	}

	public long getIdhistorylogcall() {
		return this.idhistorylogcall;
	}

	public void setIdhistorylogcall(long idhistorylogcall) {
		this.idhistorylogcall = idhistorylogcall;
	}

	public Logcall getLogcall() {
		return this.logcall;
	}

	public void setLogcall(Logcall logcall) {
		this.logcall = logcall;
	}

	public Date getDateserver() {
		return this.dateserver;
	}

	public void setDateserver(Date dateserver) {
		this.dateserver = dateserver;
	}

	public long getIdstatecall() {
		return this.idstatecall;
	}

	public void setIdstatecall(long idstatecall) {
		this.idstatecall = idstatecall;
	}

	public String getAttempt() {
		return this.attempt;
	}

	public void setAttempt(String attempt) {
		this.attempt = attempt;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

}
