/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Isoversion generated by hbm2java
 */
public class Isoversion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idisoversion;
	private String peVersion;
	private String description;
	private Set<Messagetype> messagetypes = new HashSet<Messagetype>(0);

	public Isoversion() {
	}

	public Isoversion(long idisoversion) {
		this.idisoversion = idisoversion;
	}

	public Isoversion(long idisoversion, String description,
			Set<Messagetype> messagetypes) {
		this.idisoversion = idisoversion;
		this.description = description;
		this.messagetypes = messagetypes;
	}

	public long getIdisoversion() {
		return this.idisoversion;
	}

	public void setIdisoversion(long idisoversion) {
		this.idisoversion = idisoversion;
	}

	public String getPeVersion() {
		return this.peVersion;
	}

	public void setPeVersion(String peVersion) {
		this.peVersion = peVersion;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Messagetype> getMessagetypes() {
		return this.messagetypes;
	}

	public void setMessagetypes(Set<Messagetype> messagetypes) {
		this.messagetypes = messagetypes;
	}

}
