/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;

/**
 * Limits generated by hbm2java
 */
public class Limits implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idlimits;
	private short shippingdailyamount;
	private short withdrawaldailyamount;
	private short shippinmontlyamount;
	private short withdrawalmontlyamount;
	private BigDecimal minimumamount;
	private BigDecimal maximumamount;
	private short receivedrawdayliamount;
	private short receivewmonthlyamount;

	public Limits() {
	}

	public Limits(int idlimits, short shippingdailyamount,
			short withdrawaldailyamount, short shippinmontlyamount,
			short withdrawalmontlyamount, BigDecimal minimumamount,
			BigDecimal maximumamount) {
		this.idlimits = idlimits;
		this.shippingdailyamount = shippingdailyamount;
		this.withdrawaldailyamount = withdrawaldailyamount;
		this.shippinmontlyamount = shippinmontlyamount;
		this.withdrawalmontlyamount = withdrawalmontlyamount;
		this.minimumamount = minimumamount;
		this.maximumamount = maximumamount;
	}

	public int getIdlimits() {
		return this.idlimits;
	}

	public void setIdlimits(int idlimits) {
		this.idlimits = idlimits;
	}

	public short getShippingdailyamount() {
		return this.shippingdailyamount;
	}

	public void setShippingdailyamount(short shippingdailyamount) {
		this.shippingdailyamount = shippingdailyamount;
	}

	public short getWithdrawaldailyamount() {
		return this.withdrawaldailyamount;
	}

	public void setWithdrawaldailyamount(short withdrawaldailyamount) {
		this.withdrawaldailyamount = withdrawaldailyamount;
	}

	public short getShippinmontlyamount() {
		return this.shippinmontlyamount;
	}

	public void setShippinmontlyamount(short shippinmontlyamount) {
		this.shippinmontlyamount = shippinmontlyamount;
	}

	public short getWithdrawalmontlyamount() {
		return this.withdrawalmontlyamount;
	}

	public void setWithdrawalmontlyamount(short withdrawalmontlyamount) {
		this.withdrawalmontlyamount = withdrawalmontlyamount;
	}

	public BigDecimal getMinimumamount() {
		return this.minimumamount;
	}

	public void setMinimumamount(BigDecimal minimumamount) {
		this.minimumamount = minimumamount;
	}

	public BigDecimal getMaximumamount() {
		return this.maximumamount;
	}

	public void setMaximumamount(BigDecimal maximumamount) {
		this.maximumamount = maximumamount;
	}

	/**
	 * @return the receivedrawdayliamount
	 */
	public short getReceivedrawdayliamount() {
		return receivedrawdayliamount;
	}

	/**
	 * @param receivedrawdayliamount
	 *            the receivedrawdayliamount to set
	 */
	public void setReceivedrawdayliamount(short receivedrawdayliamount) {
		this.receivedrawdayliamount = receivedrawdayliamount;
	}

	/**
	 * @return the receivewmonthlyamount
	 */
	public short getReceivewmonthlyamount() {
		return receivewmonthlyamount;
	}

	/**
	 * @param receivewmonthlyamount
	 *            the receivewmonthlyamount to set
	 */
	public void setReceivewmonthlyamount(short receivewmonthlyamount) {
		this.receivewmonthlyamount = receivewmonthlyamount;
	}

}
