/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Logbookofactivities generated by hbm2java
 */
public class Logbookofactivities implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idlogbookofactivities;
	private Employee employee;
	private Serializable dateserver;
	private Serializable checkin;
	private Serializable checkout;

	public Logbookofactivities() {
	}

	public Logbookofactivities(long idlogbookofactivities, Employee employee,
			Serializable dateserver) {
		this.idlogbookofactivities = idlogbookofactivities;
		this.employee = employee;
		this.dateserver = dateserver;
	}

	public Logbookofactivities(long idlogbookofactivities, Employee employee,
			Serializable dateserver, Serializable checkin, Serializable checkout) {
		this.idlogbookofactivities = idlogbookofactivities;
		this.employee = employee;
		this.dateserver = dateserver;
		this.checkin = checkin;
		this.checkout = checkout;
	}

	public long getIdlogbookofactivities() {
		return this.idlogbookofactivities;
	}

	public void setIdlogbookofactivities(long idlogbookofactivities) {
		this.idlogbookofactivities = idlogbookofactivities;
	}

	public Employee getEmployee() {
		return this.employee;
	}

	public void setEmployee(Employee employee) {
		this.employee = employee;
	}

	public Serializable getDateserver() {
		return this.dateserver;
	}

	public void setDateserver(Serializable dateserver) {
		this.dateserver = dateserver;
	}

	public Serializable getCheckin() {
		return this.checkin;
	}

	public void setCheckin(Serializable checkin) {
		this.checkin = checkin;
	}

	public Serializable getCheckout() {
		return this.checkout;
	}

	public void setCheckout(Serializable checkout) {
		this.checkout = checkout;
	}

}
