/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Logcall generated by hbm2java
 */
public class Logcall implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idlogcall;
	private Statecall statecall;
	private Date dateserver;
	private String attempt;
	private String username;
	private Set<Customerregistration> customerregistrations = new HashSet<Customerregistration>(
			0);
	private Set<Historylogcall> historylogcalls = new HashSet<Historylogcall>(0);

	public Logcall() {
	}

	public Logcall(long idlogcall, Statecall statecall, Date dateserver) {
		this.idlogcall = idlogcall;
		this.statecall = statecall;
		this.dateserver = dateserver;
	}

	public Logcall(long idlogcall, Statecall statecall, Date dateserver,
			String attempt, String username,
			Set<Customerregistration> customerregistrations,
			Set<Historylogcall> historylogcalls) {
		this.idlogcall = idlogcall;
		this.statecall = statecall;
		this.dateserver = dateserver;
		this.attempt = attempt;
		this.username = username;
		this.customerregistrations = customerregistrations;
		this.historylogcalls = historylogcalls;
	}

	public long getIdlogcall() {
		return this.idlogcall;
	}

	public void setIdlogcall(long idlogcall) {
		this.idlogcall = idlogcall;
	}

	public Statecall getStatecall() {
		return this.statecall;
	}

	public void setStatecall(Statecall statecall) {
		this.statecall = statecall;
	}

	public Date getDateserver() {
		return this.dateserver;
	}

	public void setDateserver(Date dateserver) {
		this.dateserver = dateserver;
	}

	public String getAttempt() {
		return this.attempt;
	}

	public void setAttempt(String attempt) {
		this.attempt = attempt;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Set<Customerregistration> getCustomerregistrations() {
		return this.customerregistrations;
	}

	public void setCustomerregistrations(
			Set<Customerregistration> customerregistrations) {
		this.customerregistrations = customerregistrations;
	}

	public Set<Historylogcall> getHistorylogcalls() {
		return this.historylogcalls;
	}

	public void setHistorylogcalls(Set<Historylogcall> historylogcalls) {
		this.historylogcalls = historylogcalls;
	}

}
