/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Messagefunction generated by hbm2java
 */
public class Messagefunction implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idmessagefunction;
	private String function;
	private String description;
	private Set<Messagetype> messagetypes = new HashSet<Messagetype>(0);

	public Messagefunction() {
	}

	public Messagefunction(long idmessagefunction) {
		this.idmessagefunction = idmessagefunction;
	}

	public Messagefunction(long idmessagefunction, String function,
			String description, Set<Messagetype> messagetypes) {
		this.idmessagefunction = idmessagefunction;
		this.function = function;
		this.description = description;
		this.messagetypes = messagetypes;
	}

	public long getIdmessagefunction() {
		return this.idmessagefunction;
	}

	public void setIdmessagefunction(long idmessagefunction) {
		this.idmessagefunction = idmessagefunction;
	}

	public String getFunction() {
		return this.function;
	}

	public void setFunction(String function) {
		this.function = function;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Messagetype> getMessagetypes() {
		return this.messagetypes;
	}

	public void setMessagetypes(Set<Messagetype> messagetypes) {
		this.messagetypes = messagetypes;
	}

}
