/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Messagetype generated by hbm2java
 */
public class Messagetype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idmessagetype;
	private String MTI;
	private Messageorigin messageorigin;
	private Isoversion isoversion;
	private Messageclass messageclass;
	private Messagefunction messagefunction;
	private Set<Transactiondetail> transactiondetails = new HashSet<Transactiondetail>(
			0);
	private Set<Messagestructure> messagestructures = new HashSet<Messagestructure>(
			0);

	public Messagetype() {
	}

	public Messagetype(long idmessagetype, Messageorigin messageorigin,
			Isoversion isoversion, Messageclass messageclass,
			Messagefunction messagefunction) {
		this.idmessagetype = idmessagetype;
		this.messageorigin = messageorigin;
		this.isoversion = isoversion;
		this.messageclass = messageclass;
		this.messagefunction = messagefunction;
	}

	public Messagetype(long idmessagetype, Messageorigin messageorigin,
			Isoversion isoversion, Messageclass messageclass,
			Messagefunction messagefunction,
			Set<Transactiondetail> transactiondetails,
			Set<Messagestructure> messagestructures) {
		this.idmessagetype = idmessagetype;
		this.messageorigin = messageorigin;
		this.isoversion = isoversion;
		this.messageclass = messageclass;
		this.messagefunction = messagefunction;
		this.transactiondetails = transactiondetails;
		this.messagestructures = messagestructures;
	}

	public long getIdmessagetype() {
		return this.idmessagetype;
	}

	public void setIdmessagetype(long idmessagetype) {
		this.idmessagetype = idmessagetype;
	}

	public Messageorigin getMessageorigin() {
		return this.messageorigin;
	}

	public void setMessageorigin(Messageorigin messageorigin) {
		this.messageorigin = messageorigin;
	}

	public Isoversion getIsoversion() {
		return this.isoversion;
	}

	public void setIsoversion(Isoversion isoversion) {
		this.isoversion = isoversion;
	}

	public Messageclass getMessageclass() {
		return this.messageclass;
	}

	public void setMessageclass(Messageclass messageclass) {
		this.messageclass = messageclass;
	}

	public Messagefunction getMessagefunction() {
		return this.messagefunction;
	}

	public void setMessagefunction(Messagefunction messagefunction) {
		this.messagefunction = messagefunction;
	}

	public Set<Transactiondetail> getTransactiondetails() {
		return this.transactiondetails;
	}

	public void setTransactiondetails(Set<Transactiondetail> transactiondetails) {
		this.transactiondetails = transactiondetails;
	}

	public Set<Messagestructure> getMessagestructures() {
		return this.messagestructures;
	}

	public void setMessagestructures(Set<Messagestructure> messagestructures) {
		this.messagestructures = messagestructures;
	}

	/**
	 * @return the mTI
	 */
	public String getMTI() {
		return MTI;
	}

	/**
	 * @param mTI
	 *            the mTI to set
	 */
	public void setMTI(String mTI) {
		MTI = mTI;
	}

}
