/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Messageorigin generated by hbm2java
 */
public class Messageorigin implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idmessageorigin;
	private String origin;
	private String description;
	private Set<Messagetype> messagetypes = new HashSet<Messagetype>(0);

	public Messageorigin() {
	}

	public Messageorigin(long idmessageorigin) {
		this.idmessageorigin = idmessageorigin;
	}

	public Messageorigin(long idmessageorigin, String origin,
			String description, Set<Messagetype> messagetypes) {
		this.idmessageorigin = idmessageorigin;
		this.origin = origin;
		this.description = description;
		this.messagetypes = messagetypes;
	}

	public long getIdmessageorigin() {
		return this.idmessageorigin;
	}

	public void setIdmessageorigin(long idmessageorigin) {
		this.idmessageorigin = idmessageorigin;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Messagetype> getMessagetypes() {
		return this.messagetypes;
	}

	public void setMessagetypes(Set<Messagetype> messagetypes) {
		this.messagetypes = messagetypes;
	}

}
