/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

/**
 * Messagefields generated by hbm2java
 */
public class Messagefields implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idMessageField;
	private Fields fields;
	private Messagestructure messagestructure;

	public Messagefields() {
	}

	public Messagefields(int idMessageField) {
		this.idMessageField = idMessageField;
	}

	public Messagefields(int idMessageField, Fields fields,
			Messagestructure messagestructure) {
		this.idMessageField = idMessageField;
		this.fields = fields;
		this.messagestructure = messagestructure;
	}

	public int getIdMessageField() {
		return this.idMessageField;
	}

	public void setIdMessageField(int idMessageField) {
		this.idMessageField = idMessageField;
	}

	public Fields getFields() {
		return this.fields;
	}


	public Messagestructure getMessagestructure() {
		return this.messagestructure;
	}

	public void setMessagestructure(Messagestructure messagestructure) {
		this.messagestructure = messagestructure;
	}

	/**
	 * @param fields the fields to set
	 */
	public void setFields(Fields fields) {
		this.fields = fields;
	}

}