/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Municipios generated by hbm2java
 */
public class Municipios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idMunicipio;
	private Estados estados;
	private String nombre;
	private String usuarioBd;
	private Date fechaModificacion;
	private Set<Colonias> coloniases = new HashSet<Colonias>(0);

	public Municipios() {
	}

	public Municipios(long idMunicipio, Estados estados, String nombre,
			String usuarioBd, Date fechaModificacion) {
		this.idMunicipio = idMunicipio;
		this.estados = estados;
		this.nombre = nombre;
		this.usuarioBd = usuarioBd;
		this.fechaModificacion = fechaModificacion;
	}

	public Municipios(long idMunicipio, Estados estados, String nombre,
			String usuarioBd, Date fechaModificacion, Set<Colonias> coloniases) {
		this.idMunicipio = idMunicipio;
		this.estados = estados;
		this.nombre = nombre;
		this.usuarioBd = usuarioBd;
		this.fechaModificacion = fechaModificacion;
		this.coloniases = coloniases;
	}

	public long getIdMunicipio() {
		return this.idMunicipio;
	}

	public void setIdMunicipio(long idMunicipio) {
		this.idMunicipio = idMunicipio;
	}

	public Estados getEstados() {
		return this.estados;
	}

	public void setEstados(Estados estados) {
		this.estados = estados;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUsuarioBd() {
		return this.usuarioBd;
	}

	public void setUsuarioBd(String usuarioBd) {
		this.usuarioBd = usuarioBd;
	}

	public Date getFechaModificacion() {
		return this.fechaModificacion;
	}

	public void setFechaModificacion(Date fechaModificacion) {
		this.fechaModificacion = fechaModificacion;
	}

	public Set<Colonias> getColoniases() {
		return this.coloniases;
	}

	public void setColoniases(Set<Colonias> coloniases) {
		this.coloniases = coloniases;
	}

}
