/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Panentrymode generated by hbm2java
 */
public class Panentrymode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idpanentrymode;
	private String entrymode;
	private String description;
	private Set<Posentrymode> posentrymodes = new HashSet<Posentrymode>(0);

	public Panentrymode() {
	}

	public Panentrymode(long idpanentrymode, String entrymode) {
		this.idpanentrymode = idpanentrymode;
		this.entrymode = entrymode;
	}

	public Panentrymode(long idpanentrymode, String entrymode,
			String description, Set<Posentrymode> posentrymodes) {
		this.idpanentrymode = idpanentrymode;
		this.entrymode = entrymode;
		this.description = description;
		this.posentrymodes = posentrymodes;
	}

	public long getIdpanentrymode() {
		return this.idpanentrymode;
	}

	public void setIdpanentrymode(long idpanentrymode) {
		this.idpanentrymode = idpanentrymode;
	}

	public String getEntrymode() {
		return this.entrymode;
	}

	public void setEntrymode(String entrymode) {
		this.entrymode = entrymode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Posentrymode> getPosentrymodes() {
		return this.posentrymodes;
	}

	public void setPosentrymodes(Set<Posentrymode> posentrymodes) {
		this.posentrymodes = posentrymodes;
	}

}
