/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Partnershop generated by hbm2java
 */
public class Partnershop implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idpartnershops;
	private Partner partner;
	private Long idDomicilio;
	private long affiliationpesoexpress;
	private Serializable datemodified;
	private String username;
	private short isactivied;
	private BigDecimal commision;
	private Boolean fixedporcentaje;
	private Set<Terminal> terminals = new HashSet<Terminal>(0);

	public Partnershop() {
	}

	public Partnershop(int idpartnershops, Partner partner,
			int affiliationpesoexpress, Serializable datemodified,
			String username, short isactivied) {
		this.idpartnershops = idpartnershops;
		this.partner = partner;
		this.affiliationpesoexpress = affiliationpesoexpress;
		this.datemodified = datemodified;
		this.username = username;
		this.isactivied = isactivied;
	}

	public Partnershop(int idpartnershops, Partner partner, Long idDomicilio,
			int affiliationpesoexpress, Serializable datemodified,
			String username, short isactivied, Set<Terminal> terminals,
			BigDecimal commision, Boolean fixedporcentaje) {
		this.idpartnershops = idpartnershops;
		this.partner = partner;
		this.idDomicilio = idDomicilio;
		this.affiliationpesoexpress = affiliationpesoexpress;
		this.datemodified = datemodified;
		this.username = username;
		this.isactivied = isactivied;
		this.commision = commision;
		this.fixedporcentaje = fixedporcentaje;
		this.terminals = terminals;
	}

	public int getIdpartnershops() {
		return this.idpartnershops;
	}

	public void setIdpartnershops(int idpartnershops) {
		this.idpartnershops = idpartnershops;
	}

	public Partner getPartner() {
		return this.partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	public long getIdDomicilio() {
		return this.idDomicilio;
	}

	public void setIdDomicilio(long idDomicilio) {
		this.idDomicilio = idDomicilio;
	}

	public long getAffiliationpesoexpress() {
		return this.affiliationpesoexpress;
	}

	public void setAffiliationpesoexpress(long affiliationpesoexpress) {
		this.affiliationpesoexpress = affiliationpesoexpress;
	}

	public Serializable getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Serializable datemodified) {
		this.datemodified = datemodified;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public short getIsactivied() {
		return isactivied;
	}

	public void setIsactivied(short isactivied) {
		this.isactivied = isactivied;
	}

	public BigDecimal getCommision() {
		return this.commision;
	}

	public void setCommision(BigDecimal commision) {
		this.commision = commision;
	}

	public Boolean getFixedporcentaje() {
		return this.fixedporcentaje;
	}

	public void setFixedporcentaje(Boolean fixedporcentaje) {
		this.fixedporcentaje = fixedporcentaje;
	}

	public Set<Terminal> getTerminals() {
		return this.terminals;
	}

	public void setTerminals(Set<Terminal> terminals) {
		this.terminals = terminals;
	}

}
