/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Partner generated by hbm2java
 */
public class Partner implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idpartner;
	private Domicilios domicilios;
	private String company;
	private String companyname;
	private String commercialbusiness;
	private String rfc;
	private Long fax;
	private Long telephone;
	private long affiliationpesoexpress;
	private Serializable datemodified;
	private String username;
	private short isactivied;
	private BigDecimal commision;
	private Boolean fixedporcentaje;
	private Set<Partnershop> partnershops = new HashSet<Partnershop>(0);
	private Set<Scalingmatrix> scalingmatrixes = new HashSet<Scalingmatrix>(0);

	public Partner() {
	}

	public Partner(int idpartner, String company, String companyname,
			String commercialbusiness, String rfc,
			short affiliationpesoexpress, Serializable datemodified,
			String username, short isactivied, BigDecimal commision) {
		this.idpartner = idpartner;
		this.company = company;
		this.companyname = companyname;
		this.commercialbusiness = commercialbusiness;
		this.rfc = rfc;
		this.affiliationpesoexpress = affiliationpesoexpress;
		this.datemodified = datemodified;
		this.username = username;
		this.isactivied = isactivied;
		this.commision = commision;
	}

	public Partner(int idpartner, Domicilios domicilios, String company,
			String companyname, String commercialbusiness, String rfc,
			Long fax, Long telephone, short affiliationpesoexpress,
			Serializable datemodified, String username, short isactivied,
			Set<Partnershop> partnershops, Set<Scalingmatrix> scalingmatrixes,
			BigDecimal commision, Boolean fixedporcentaje) {
		this.idpartner = idpartner;
		this.domicilios = domicilios;
		this.company = company;
		this.companyname = companyname;
		this.commercialbusiness = commercialbusiness;
		this.rfc = rfc;
		this.fax = fax;
		this.telephone = telephone;
		this.affiliationpesoexpress = affiliationpesoexpress;
		this.datemodified = datemodified;
		this.username = username;
		this.isactivied = isactivied;
		this.commision = commision;
		this.fixedporcentaje = fixedporcentaje;
		this.partnershops = partnershops;
		this.scalingmatrixes = scalingmatrixes;
	}

	public int getIdpartner() {
		return idpartner;
	}

	public void setIdpartner(int idpartner) {
		this.idpartner = idpartner;
	}

	public Domicilios getDomicilios() {
		return domicilios;
	}

	public void setDomicilios(Domicilios domicilios) {
		this.domicilios = domicilios;
	}

	public String getCompany() {
		return company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getCompanyname() {
		return companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	public String getCommercialbusiness() {
		return commercialbusiness;
	}

	public void setCommercialbusiness(String commercialbusiness) {
		this.commercialbusiness = commercialbusiness;
	}

	public String getRfc() {
		return rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public Long getFax() {
		return fax;
	}

	public void setFax(Long fax) {
		this.fax = fax;
	}

	public Long getTelephone() {
		return telephone;
	}

	public void setTelephone(Long telephone) {
		this.telephone = telephone;
	}

	public long getAffiliationpesoexpress() {
		return affiliationpesoexpress;
	}

	public void setAffiliationpesoexpress(long affiliationpesoexpress) {
		this.affiliationpesoexpress = affiliationpesoexpress;
	}

	public Serializable getDatemodified() {
		return datemodified;
	}

	public void setDatemodified(Serializable datemodified) {
		this.datemodified = datemodified;
	}

	public String getUsername() {
		return username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public short getIsactivied() {
		return isactivied;
	}

	public void setIsactivied(short isactivied) {
		this.isactivied = isactivied;
	}

	public BigDecimal getCommision() {
		return commision;
	}

	public void setCommision(BigDecimal commision) {
		this.commision = commision;
	}

	public Boolean getFixedporcentaje() {
		return fixedporcentaje;
	}

	public void setFixedporcentaje(Boolean fixedporcentaje) {
		this.fixedporcentaje = fixedporcentaje;
	}

	public Set<Partnershop> getPartnershops() {
		return partnershops;
	}

	public void setPartnershops(Set<Partnershop> partnershops) {
		this.partnershops = partnershops;
	}

	public Set<Scalingmatrix> getScalingmatrixes() {
		return scalingmatrixes;
	}

	public void setScalingmatrixes(Set<Scalingmatrix> scalingmatrixes) {
		this.scalingmatrixes = scalingmatrixes;
	}

}
