/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Pebranch generated by hbm2java
 */
public class Pebranch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idpebranch;
	private Domicilios domicilios;
	private Pecompany pecompany;
	private Workday workday;
	private Long telephone;
	private String email;
	private Serializable datemodified;
	private String username;
	private boolean isactivied;
	private Set<Workinggroup> workinggroups = new HashSet<Workinggroup>(0);

	public Pebranch() {
	}

	public Pebranch(long idpebranch, Pecompany pecompany, Workday workday,
			Serializable datemodified, String username, boolean isactivied) {
		this.idpebranch = idpebranch;
		this.pecompany = pecompany;
		this.workday = workday;
		this.datemodified = datemodified;
		this.username = username;
		this.isactivied = isactivied;
	}

	public Pebranch(long idpebranch, Domicilios domicilios,
			Pecompany pecompany, Workday workday, Long telephone, String email,
			Serializable datemodified, String username, boolean isactivied,
			Set<Workinggroup> workinggroups) {
		this.idpebranch = idpebranch;
		this.domicilios = domicilios;
		this.pecompany = pecompany;
		this.workday = workday;
		this.telephone = telephone;
		this.email = email;
		this.datemodified = datemodified;
		this.username = username;
		this.isactivied = isactivied;
		this.workinggroups = workinggroups;
	}

	public long getIdpebranch() {
		return this.idpebranch;
	}

	public void setIdpebranch(long idpebranch) {
		this.idpebranch = idpebranch;
	}

	public Domicilios getDomicilios() {
		return this.domicilios;
	}

	public void setDomicilios(Domicilios domicilios) {
		this.domicilios = domicilios;
	}

	public Pecompany getPecompany() {
		return this.pecompany;
	}

	public void setPecompany(Pecompany pecompany) {
		this.pecompany = pecompany;
	}

	public Workday getWorkday() {
		return this.workday;
	}

	public void setWorkday(Workday workday) {
		this.workday = workday;
	}

	public Long getTelephone() {
		return this.telephone;
	}

	public void setTelephone(Long telephone) {
		this.telephone = telephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Serializable getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Serializable datemodified) {
		this.datemodified = datemodified;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean isIsactivied() {
		return this.isactivied;
	}

	public void setIsactivied(boolean isactivied) {
		this.isactivied = isactivied;
	}

	public Set<Workinggroup> getWorkinggroups() {
		return this.workinggroups;
	}

	public void setWorkinggroups(Set<Workinggroup> workinggroups) {
		this.workinggroups = workinggroups;
	}

}
