/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

/**
 * Peconfig generated by hbm2java
 */
public class Peconfig implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idpeconfig;
	private Peconnectiontype peconnectiontype;
	private Peservices peservices;
	private String url;
	private String ip;
	private String port;
	private short logactivated;
	private String logpath;
	private short eventactivated;
	private String eventpath;
	private String deployDir;

	public Peconfig() {
	}

	public Peconfig(long idpeconfig, Peconnectiontype peconnectiontype,
			Peservices peservices, String ip, String port, short logactivated,
			short eventactivated) {
		this.idpeconfig = idpeconfig;
		this.peconnectiontype = peconnectiontype;
		this.peservices = peservices;
		this.ip = ip;
		this.port = port;
		this.logactivated = logactivated;
		this.eventactivated = eventactivated;
	}

	public Peconfig(long idpeconfig, Peconnectiontype peconnectiontype,
			Peservices peservices, String url, String ip, String port,
			short logactivated, String logpath, short eventactivated,
			String eventpath) {
		this.idpeconfig = idpeconfig;
		this.peconnectiontype = peconnectiontype;
		this.peservices = peservices;
		this.url = url;
		this.ip = ip;
		this.port = port;
		this.logactivated = logactivated;
		this.logpath = logpath;
		this.eventactivated = eventactivated;
		this.eventpath = eventpath;
	}

	public long getIdpeconfig() {
		return this.idpeconfig;
	}

	public void setIdpeconfig(long idpeconfig) {
		this.idpeconfig = idpeconfig;
	}

	public Peconnectiontype getPeconnectiontype() {
		return this.peconnectiontype;
	}

	public void setPeconnectiontype(Peconnectiontype peconnectiontype) {
		this.peconnectiontype = peconnectiontype;
	}

	public Peservices getPeservices() {
		return this.peservices;
	}

	public void setPeservices(Peservices peservices) {
		this.peservices = peservices;
	}

	public String getUrl() {
		return this.url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getIp() {
		return this.ip;
	}

	public void setIp(String ip) {
		this.ip = ip;
	}

	public String getPort() {
		return this.port;
	}

	public void setPort(String port) {
		this.port = port;
	}

	public String getLogpath() {
		return this.logpath;
	}

	public void setLogpath(String logpath) {
		this.logpath = logpath;
	}

	public String getEventpath() {
		return this.eventpath;
	}

	public void setEventpath(String eventpath) {
		this.eventpath = eventpath;
	}

	/**
	 * @return the logactivated
	 */
	public short getLogactivated() {
		return logactivated;
	}

	/**
	 * @param logactivated
	 *            the logactivated to set
	 */
	public void setLogactivated(short logactivated) {
		this.logactivated = logactivated;
	}

	/**
	 * @return the eventactivated
	 */
	public short getEventactivated() {
		return eventactivated;
	}

	/**
	 * @param eventactivated
	 *            the eventactivated to set
	 */
	public void setEventactivated(short eventactivated) {
		this.eventactivated = eventactivated;
	}

	/**
	 * @return the deployDir
	 */
	public String getDeployDir() {
		return deployDir;
	}

	/**
	 * @param deployDir
	 *            the deployDir to set
	 */
	public void setDeployDir(String deployDir) {
		this.deployDir = deployDir;
	}

}
