/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

/**
 * Peconnectiontype generated by hbm2java
 */
public class Peconnectiontype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idpeconnectiontype;
	private String type;
	private String description;

	public Peconnectiontype() {
	}

	public Peconnectiontype(long idpeconnectiontype, String type) {
		this.idpeconnectiontype = idpeconnectiontype;
		this.type = type;
	}

	public Peconnectiontype(long idpeconnectiontype, String type,
			String description) {
		this.idpeconnectiontype = idpeconnectiontype;
		this.type = type;
		this.description = description;
	}

	public long getIdpeconnectiontype() {
		return this.idpeconnectiontype;
	}

	public void setIdpeconnectiontype(long idpeconnectiontype) {
		this.idpeconnectiontype = idpeconnectiontype;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
