/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Pecompany generated by hbm2java
 */
public class Pecompany implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idpecompany;
	private Domicilios domicilios;
	private String company;
	private String companyname;
	private String commercialbusiness;
	private String rfc;
	private Long fax;
	private Long telephone;
	private String email;
	private Serializable datemodified;
	private String username;
	private boolean isactivied;
	private Set<Pebranch> pebranches = new HashSet<Pebranch>(0);

	public Pecompany() {
	}

	public Pecompany(long idpecompay, Serializable datemodified,
			String username, boolean isactivied) {
		this.idpecompany = idpecompay;
		this.datemodified = datemodified;
		this.username = username;
		this.isactivied = isactivied;
	}

	public Pecompany(long idpecompay, Domicilios domicilios, String company,
			String companyname, String commercialbusiness, String rfc,
			Long fax, Long telephone, String email, Serializable datemodified,
			String username, boolean isactivied, Set<Pebranch> pebranches) {
		this.idpecompany = idpecompay;
		this.domicilios = domicilios;
		this.company = company;
		this.companyname = companyname;
		this.commercialbusiness = commercialbusiness;
		this.rfc = rfc;
		this.fax = fax;
		this.telephone = telephone;
		this.email = email;
		this.datemodified = datemodified;
		this.username = username;
		this.isactivied = isactivied;
		this.pebranches = pebranches;
	}

	public long getIdpecompany() {
		return this.idpecompany;
	}

	public void setIdpecompany(long idpecompany) {
		this.idpecompany = idpecompany;
	}

	public Domicilios getDomicilios() {
		return this.domicilios;
	}

	public void setDomicilios(Domicilios domicilios) {
		this.domicilios = domicilios;
	}

	public String getCompany() {
		return this.company;
	}

	public void setCompany(String company) {
		this.company = company;
	}

	public String getCompanyname() {
		return this.companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	public String getCommercialbusiness() {
		return this.commercialbusiness;
	}

	public void setCommercialbusiness(String commercialbusiness) {
		this.commercialbusiness = commercialbusiness;
	}

	public String getRfc() {
		return this.rfc;
	}

	public void setRfc(String rfc) {
		this.rfc = rfc;
	}

	public Long getFax() {
		return this.fax;
	}

	public void setFax(Long fax) {
		this.fax = fax;
	}

	public Long getTelephone() {
		return this.telephone;
	}

	public void setTelephone(Long telephone) {
		this.telephone = telephone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Serializable getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Serializable datemodified) {
		this.datemodified = datemodified;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean isIsactivied() {
		return this.isactivied;
	}

	public void setIsactivied(boolean isactivied) {
		this.isactivied = isactivied;
	}

	public Set<Pebranch> getPebranches() {
		return this.pebranches;
	}

	public void setPebranches(Set<Pebranch> pebranches) {
		this.pebranches = pebranches;
	}

}
