/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

/**
 * Pinconditions generated by hbm2java
 */
public class Pinconditions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idpinconditions;
	private String conditions;
	private String description;
	private String additonaldata1;
	private String additonaldata2;
	private String additonaldata3;
	private String additonaldata4;
	private String additonaldata5;

	public Pinconditions() {
	}

	public Pinconditions(long idpinconditions, String conditions,
			String description) {
		this.idpinconditions = idpinconditions;
		this.conditions = conditions;
		this.description = description;
	}

	public Pinconditions(long idpinconditions, String conditions,
			String description, String additonaldata1, String additonaldata2,
			String additonaldata3, String additonaldata4, String additonaldata5) {
		this.idpinconditions = idpinconditions;
		this.conditions = conditions;
		this.description = description;
		this.additonaldata1 = additonaldata1;
		this.additonaldata2 = additonaldata2;
		this.additonaldata3 = additonaldata3;
		this.additonaldata4 = additonaldata4;
		this.additonaldata5 = additonaldata5;
	}

	public long getIdpinconditions() {
		return this.idpinconditions;
	}

	public void setIdpinconditions(long idpinconditions) {
		this.idpinconditions = idpinconditions;
	}

	public String getConditions() {
		return this.conditions;
	}

	public void setConditions(String conditions) {
		this.conditions = conditions;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAdditonaldata1() {
		return this.additonaldata1;
	}

	public void setAdditonaldata1(String additonaldata1) {
		this.additonaldata1 = additonaldata1;
	}

	public String getAdditonaldata2() {
		return this.additonaldata2;
	}

	public void setAdditonaldata2(String additonaldata2) {
		this.additonaldata2 = additonaldata2;
	}

	public String getAdditonaldata3() {
		return this.additonaldata3;
	}

	public void setAdditonaldata3(String additonaldata3) {
		this.additonaldata3 = additonaldata3;
	}

	public String getAdditonaldata4() {
		return this.additonaldata4;
	}

	public void setAdditonaldata4(String additonaldata4) {
		this.additonaldata4 = additonaldata4;
	}

	public String getAdditonaldata5() {
		return this.additonaldata5;
	}

	public void setAdditonaldata5(String additonaldata5) {
		this.additonaldata5 = additonaldata5;
	}

}
