/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pinentrycapability generated by hbm2java
 */
public class Pinentrycapability implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idpinentrycapability;
	private String entrycapability;
	private String description;
	private Set<Posentrymode> posentrymodes = new HashSet<Posentrymode>(0);

	public Pinentrycapability() {
	}

	public Pinentrycapability(long idpinentrycapability, String entrycapability) {
		this.idpinentrycapability = idpinentrycapability;
		this.entrycapability = entrycapability;
	}

	public Pinentrycapability(long idpinentrycapability,
			String entrycapability, String description,
			Set<Posentrymode> posentrymodes) {
		this.idpinentrycapability = idpinentrycapability;
		this.entrycapability = entrycapability;
		this.description = description;
		this.posentrymodes = posentrymodes;
	}

	public long getIdpinentrycapability() {
		return this.idpinentrycapability;
	}

	public void setIdpinentrycapability(long idpinentrycapability) {
		this.idpinentrycapability = idpinentrycapability;
	}

	public String getEntrycapability() {
		return this.entrycapability;
	}

	public void setEntrycapability(String entrycapability) {
		this.entrycapability = entrycapability;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Posentrymode> getPosentrymodes() {
		return this.posentrymodes;
	}

	public void setPosentrymodes(Set<Posentrymode> posentrymodes) {
		this.posentrymodes = posentrymodes;
	}

}
