/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Pinsecurity generated by hbm2java
 */
public class Pinsecurity implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idpinsecurity;
	private String pinsecurity;
	private int active;
	private Set<Transactions> transactionses = new HashSet<Transactions>(0);

	public Pinsecurity() {
	}

	public Pinsecurity(long idpinsecurity, String pinsecurity, short isactive) {
		this.idpinsecurity = idpinsecurity;
		this.pinsecurity = pinsecurity;
		this.active = isactive;
	}

	public Pinsecurity(long idpinsecurity, String pinsecurity, short isactive,
			Set<Transactions> transactionses) {
		this.idpinsecurity = idpinsecurity;
		this.pinsecurity = pinsecurity;
		this.active = isactive;
		this.transactionses = transactionses;
	}

	public long getIdpinsecurity() {
		return this.idpinsecurity;
	}

	public void setIdpinsecurity(long idpinsecurity) {
		this.idpinsecurity = idpinsecurity;
	}

	public String getPinsecurity() {
		return this.pinsecurity;
	}

	public void setPinsecurity(String pinsecurity) {
		this.pinsecurity = pinsecurity;
	}

	public Set<Transactions> getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set<Transactions> transactionses) {
		this.transactionses = transactionses;
	}

	/**
	 * @return the active
	 */
	public int getActive() {
		return active;
	}

	/**
	 * @param active
	 *            the active to set
	 */
	public void setActive(int active) {
		this.active = active;
	}

}
