/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Processingcode generated by hbm2java
 */
public class Processingcode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idprocessingcode;
	private Accounttype accounttypeByIdaccounttypefrom;
	private Accounttype accounttypeByIdaccounttypeto;
	private Transactiontype transactiontype;
	private String description;
	private Set<Responsecodes> responsecodeses = new HashSet<Responsecodes>(0);
	private Set<Transactiondetail> transactiondetails = new HashSet<Transactiondetail>(
			0);
	private Set<Messagefactory> messagefactories = new HashSet<Messagefactory>(
			0);

	public Processingcode() {
	}

	public Processingcode(int idprocessingcode,
			Accounttype accounttypeByIdaccounttypefrom,
			Accounttype accounttypeByIdaccounttypeto,
			Transactiontype transactiontype) {
		this.idprocessingcode = idprocessingcode;
		this.accounttypeByIdaccounttypefrom = accounttypeByIdaccounttypefrom;
		this.accounttypeByIdaccounttypeto = accounttypeByIdaccounttypeto;
		this.transactiontype = transactiontype;
	}

	public Processingcode(int idprocessingcode,
			Accounttype accounttypeByIdaccounttypefrom,
			Accounttype accounttypeByIdaccounttypeto,
			Transactiontype transactiontype, String description,
			Set<Responsecodes> responsecodeses,
			Set<Transactiondetail> transactiondetails,
			Set<Messagefactory> messagefactories) {
		this.idprocessingcode = idprocessingcode;
		this.accounttypeByIdaccounttypefrom = accounttypeByIdaccounttypefrom;
		this.accounttypeByIdaccounttypeto = accounttypeByIdaccounttypeto;
		this.transactiontype = transactiontype;
		this.description = description;
		this.responsecodeses = responsecodeses;
		this.transactiondetails = transactiondetails;
		this.messagefactories = messagefactories;
	}

	public int getIdprocessingcode() {
		return this.idprocessingcode;
	}

	public void setIdprocessingcode(int idprocessingcode) {
		this.idprocessingcode = idprocessingcode;
	}

	public Accounttype getAccounttypeByIdaccounttypefrom() {
		return this.accounttypeByIdaccounttypefrom;
	}

	public void setAccounttypeByIdaccounttypefrom(
			Accounttype accounttypeByIdaccounttypefrom) {
		this.accounttypeByIdaccounttypefrom = accounttypeByIdaccounttypefrom;
	}

	public Accounttype getAccounttypeByIdaccounttypeto() {
		return this.accounttypeByIdaccounttypeto;
	}

	public void setAccounttypeByIdaccounttypeto(
			Accounttype accounttypeByIdaccounttypeto) {
		this.accounttypeByIdaccounttypeto = accounttypeByIdaccounttypeto;
	}

	public Transactiontype getTransactiontype() {
		return this.transactiontype;
	}

	public void setTransactiontype(Transactiontype transactiontype) {
		this.transactiontype = transactiontype;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Responsecodes> getResponsecodeses() {
		return this.responsecodeses;
	}

	public void setResponsecodeses(Set<Responsecodes> responsecodeses) {
		this.responsecodeses = responsecodeses;
	}

	public Set<Transactiondetail> getTransactiondetails() {
		return this.transactiondetails;
	}

	public void setTransactiondetails(Set<Transactiondetail> transactiondetails) {
		this.transactiondetails = transactiondetails;
	}

	public Set<Messagefactory> getMessagefactories() {
		return this.messagefactories;
	}

	public void setMessagefactories(Set<Messagefactory> messagefactories) {
		this.messagefactories = messagefactories;
	}

}
