/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

/**
 * Responsecodes generated by hbm2java
 */
public class Responsecodes implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idresponsecodes;
	private Processingcode processingcode;
	private String responsecode;
	private String description;

	public Responsecodes() {
	}

	public Responsecodes(int idresponsecodes, Processingcode processingcode,
			String responsecode, String description) {
		this.idresponsecodes = idresponsecodes;
		this.processingcode = processingcode;
		this.responsecode = responsecode;
		this.description = description;
	}

	public int getIdresponsecodes() {
		return this.idresponsecodes;
	}

	public void setIdresponsecodes(int idresponsecodes) {
		this.idresponsecodes = idresponsecodes;
	}

	public Processingcode getProcessingcode() {
		return this.processingcode;
	}

	public void setProcessingcode(Processingcode processingcode) {
		this.processingcode = processingcode;
	}

	public String getResponsecode() {
		return this.responsecode;
	}

	public void setResponsecode(String responsecode) {
		this.responsecode = responsecode;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
