/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Scalingmatrix generated by hbm2java
 */
public class Scalingmatrix implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idscalingmatrix;
	private Partner partner;
	private int pelevel;
	private String name;
	private String surname;
	private String workstation;
	private String contactemail;
	private long celnumber;
	private long telnumber;
	private int extension;
	private Serializable datemodified;
	private String username;
	private short isactivied;

	public Scalingmatrix() {
	}

	public Scalingmatrix(int idscalingmatrix, Partner partner, int pelevel,
			String name, String surname, String workstation,
			Serializable datemodified, String username, short isactivied) {
		this.idscalingmatrix = idscalingmatrix;
		this.partner = partner;
		this.pelevel = pelevel;
		this.name = name;
		this.surname = surname;
		this.workstation = workstation;
		this.datemodified = datemodified;
		this.username = username;
		this.isactivied = isactivied;
	}

	public Scalingmatrix(int idscalingmatrix, Partner partner, int pelevel,
			String name, String surname, String workstation,
			String contactemail, long celnumber, long telnumber, int extension,
			Serializable datemodified, String username, short isactivied) {
		this.idscalingmatrix = idscalingmatrix;
		this.partner = partner;
		this.pelevel = pelevel;
		this.name = name;
		this.surname = surname;
		this.workstation = workstation;
		this.contactemail = contactemail;
		this.celnumber = celnumber;
		this.telnumber = telnumber;
		this.extension = extension;
		this.datemodified = datemodified;
		this.username = username;
		this.isactivied = isactivied;
	}

	public int getIdscalingmatrix() {
		return this.idscalingmatrix;
	}

	public void setIdscalingmatrix(int idscalingmatrix) {
		this.idscalingmatrix = idscalingmatrix;
	}

	public Partner getPartner() {
		return this.partner;
	}

	public void setPartner(Partner partner) {
		this.partner = partner;
	}

	public int getPelevel() {
		return this.pelevel;
	}

	public void setPelevel(int pelevel) {
		this.pelevel = pelevel;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return this.surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getWorkstation() {
		return this.workstation;
	}

	public void setWorkstation(String workstation) {
		this.workstation = workstation;
	}

	public String getContactemail() {
		return this.contactemail;
	}

	public void setContactemail(String contactemail) {
		this.contactemail = contactemail;
	}

	public long getCelnumber() {
		return this.celnumber;
	}

	public void setCelnumber(long celnumber) {
		this.celnumber = celnumber;
	}

	public long getTelnumber() {
		return this.telnumber;
	}

	public void setTelnumber(long telnumber) {
		this.telnumber = telnumber;
	}

	public int getExtension() {
		return this.extension;
	}

	public void setExtension(int extension) {
		this.extension = extension;
	}

	public Serializable getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Serializable datemodified) {
		this.datemodified = datemodified;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public short getIsactivied() {
		return isactivied;
	}

	public void setIsactivied(short isactivied) {
		this.isactivied = isactivied;
	}

}
