/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Smsconnectiontype generated by hbm2java
 */
public class Smsconnectiontype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private byte idsmsconnectiontype;
	private String type;
	private String description;
	private Set<Smsconfig> smsconfigs = new HashSet<Smsconfig>(0);

	public Smsconnectiontype() {
	}

	public Smsconnectiontype(byte idsmsconnectiontype, String type,
			String description) {
		this.idsmsconnectiontype = idsmsconnectiontype;
		this.type = type;
		this.description = description;
	}

	public Smsconnectiontype(byte idsmsconnectiontype, String type,
			String description, Set<Smsconfig> smsconfigs) {
		this.idsmsconnectiontype = idsmsconnectiontype;
		this.type = type;
		this.description = description;
		this.smsconfigs = smsconfigs;
	}

	public byte getIdsmsconnectiontype() {
		return this.idsmsconnectiontype;
	}

	public void setIdsmsconnectiontype(byte idsmsconnectiontype) {
		this.idsmsconnectiontype = idsmsconnectiontype;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Smsconfig> getSmsconfigs() {
		return this.smsconfigs;
	}

	public void setSmsconfigs(Set<Smsconfig> smsconfigs) {
		this.smsconfigs = smsconfigs;
	}

}
