/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Smsprovider generated by hbm2java
 */
public class Smsprovider implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idsmsprovider;
	private Smsstatus smsstatus;
	private String provider;
	private int idsmsbalance;
	private Set<Smsqueue> smsqueues = new HashSet<Smsqueue>(0);
	private Set<Smsbalance> smsbalances = new HashSet<Smsbalance>(0);
	private Set<Smsconfig> smsconfigs = new HashSet<Smsconfig>(0);

	public Smsprovider() {
	}

	public Smsprovider(int idsmsprovider, Smsstatus smsstatus,
			String provider, int idsmsbalance) {
		this.idsmsprovider = idsmsprovider;
		this.smsstatus = smsstatus;
		this.provider = provider;
		this.idsmsbalance = idsmsbalance;
	}

	public Smsprovider(int idsmsprovider, Smsstatus smsstatus,
			String provider, int idsmsbalance, Set<Smsqueue> smsqueues,
			Set<Smsbalance> smsbalances, Set<Smsconfig> smsconfigs) {
		this.idsmsprovider = idsmsprovider;
		this.smsstatus = smsstatus;
		this.provider = provider;
		this.idsmsbalance = idsmsbalance;
		this.smsqueues = smsqueues;
		this.smsbalances = smsbalances;
		this.smsconfigs = smsconfigs;
	}

	public int getIdsmsprovider() {
		return this.idsmsprovider;
	}

	public void setIdsmsprovider(int idsmsprovider) {
		this.idsmsprovider = idsmsprovider;
	}

	public Smsstatus getSmsstatus() {
		return this.smsstatus;
	}

	public void setSmsstatus(Smsstatus smsstatus) {
		this.smsstatus = smsstatus;
	}

	public String getProvider() {
		return this.provider;
	}

	public void setProvider(String provider) {
		this.provider = provider;
	}

	public int getIdsmsbalance() {
		return this.idsmsbalance;
	}

	public void setIdsmsbalance(int idsmsbalance) {
		this.idsmsbalance = idsmsbalance;
	}

	public Set<Smsqueue> getSmsqueues() {
		return this.smsqueues;
	}

	public void setSmsqueues(Set<Smsqueue> smsqueues) {
		this.smsqueues = smsqueues;
	}

	public Set<Smsbalance> getSmsbalances() {
		return this.smsbalances;
	}

	public void setSmsbalances(Set<Smsbalance> smsbalances) {
		this.smsbalances = smsbalances;
	}

	public Set<Smsconfig> getSmsconfigs() {
		return this.smsconfigs;
	}

	public void setSmsconfigs(Set<Smsconfig> smsconfigs) {
		this.smsconfigs = smsconfigs;
	}

}
