/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

/**
 * Smsqueue generated by hbm2java
 */
public class Smsqueue implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idsmsqueue;
	private Smsprovider smsprovider;
	private Smsstatussend smsstatussend;
	private Transactions transactions;
	private String textticket;
	private String providerresponse;

	public Smsqueue() {
	}

	public Smsqueue(long idsmsqueue, Smsprovider smsprovider,
			Smsstatussend smsstatussend, Transactions transactions,
			String textticket) {
		this.idsmsqueue = idsmsqueue;
		this.smsprovider = smsprovider;
		this.smsstatussend = smsstatussend;
		this.transactions = transactions;
		this.textticket = textticket;
	}

	public long getIdsmsqueue() {
		return this.idsmsqueue;
	}

	public void setIdsmsqueue(long idsmsqueue) {
		this.idsmsqueue = idsmsqueue;
	}

	public Smsprovider getSmsprovider() {
		return this.smsprovider;
	}

	public void setSmsprovider(Smsprovider smsprovider) {
		this.smsprovider = smsprovider;
	}

	public Smsstatussend getSmsstatussend() {
		return this.smsstatussend;
	}

	public void setSmsstatussend(Smsstatussend smsstatussend) {
		this.smsstatussend = smsstatussend;
	}

	public Transactions getTransactions() {
		return this.transactions;
	}

	public void setTransactions(Transactions transactions) {
		this.transactions = transactions;
	}

	public String getTextticket() {
		return this.textticket;
	}

	public void setTextticket(String textticket) {
		this.textticket = textticket;
	}

	/**
	 * @return the providerresponse
	 */
	public String getProviderresponse() {
		return providerresponse;
	}

	/**
	 * @param providerresponse the providerresponse to set
	 */
	public void setProviderresponse(String providerresponse) {
		this.providerresponse = providerresponse;
	}

}
