/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Smsstatus generated by hbm2java
 */
public class Smsstatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idsmsstatus;
	private String status;
	private String description;
	private Set<Smsprovider> smsproviders = new HashSet<Smsprovider>(0);

	public Smsstatus() {
	}

	public Smsstatus(int idsmsstatus, String status, String description) {
		this.idsmsstatus = idsmsstatus;
		this.status = status;
		this.description = description;
	}

	public Smsstatus(int idsmsstatus, String status, String description,
			Set<Smsprovider> smsproviders) {
		this.idsmsstatus = idsmsstatus;
		this.status = status;
		this.description = description;
		this.smsproviders = smsproviders;
	}

	public int getIdsmsstatus() {
		return this.idsmsstatus;
	}

	public void setIdsmsstatus(int idsmsstatus) {
		this.idsmsstatus = idsmsstatus;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Smsprovider> getSmsproviders() {
		return this.smsproviders;
	}

	public void setSmsproviders(Set<Smsprovider> smsproviders) {
		this.smsproviders = smsproviders;
	}

}
