/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Smsstatussend generated by hbm2java
 */
public class Smsstatussend implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idsmsstatussend;
	private String status;
	private String description;
	private Set<Smsqueue> smsqueues = new HashSet<Smsqueue>(0);

	public Smsstatussend() {
	}

	public Smsstatussend(int idsmsstatussend, String status, String description) {
		this.idsmsstatussend = idsmsstatussend;
		this.status = status;
		this.description = description;
	}

	public Smsstatussend(int idsmsstatussend, String status,
			String description, Set<Smsqueue> smsqueues) {
		this.idsmsstatussend = idsmsstatussend;
		this.status = status;
		this.description = description;
		this.smsqueues = smsqueues;
	}

	public int getIdsmsstatussend() {
		return this.idsmsstatussend;
	}

	public void setIdsmsstatussend(int idsmsstatussend) {
		this.idsmsstatussend = idsmsstatussend;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Smsqueue> getSmsqueues() {
		return this.smsqueues;
	}

	public void setSmsqueues(Set<Smsqueue> smsqueues) {
		this.smsqueues = smsqueues;
	}

}
