/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 3/06/2014 04:35:18 PM by Hibernate Tools 3.2.1.GA

/**
 * Smstext generated by hbm2java
 */
public class Smstext implements java.io.Serializable {

	private int idSms;
	private String textSms;
	private Short activeSms;

	public Smstext() {
	}

	public Smstext(int idSms) {
		this.idSms = idSms;
	}
	
	public Smstext(int idSms, String textSms, Short activeSms) {
		this.idSms = idSms;
		this.textSms = textSms;
		this.activeSms = activeSms;
	}

	public int getIdSms() {
		return this.idSms;
	}

	public void setIdSms(int idSms) {
		this.idSms = idSms;
	}

	public String getTextSms() {
		return this.textSms;
	}

	public void setTextSms(String textSms) {
		this.textSms = textSms;
	}

	public Short getActiveSms() {
		return this.activeSms;
	}

	public void setActiveSms(Short activeSms) {
		this.activeSms = activeSms;
	}

}
