/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Stateusername generated by hbm2java
 */
public class Stateusername implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idstateusername;
	private String state;
	private String description;
	private Set<Useraccount> useraccounts = new HashSet<Useraccount>(0);

	public Stateusername() {
	}

	public Stateusername(long idstateusername, String state, String description) {
		this.idstateusername = idstateusername;
		this.state = state;
		this.description = description;
	}

	public Stateusername(long idstateusername, String state,
			String description, Set<Useraccount> useraccounts) {
		this.idstateusername = idstateusername;
		this.state = state;
		this.description = description;
		this.useraccounts = useraccounts;
	}

	public long getIdstateusername() {
		return this.idstateusername;
	}

	public void setIdstateusername(long idstateusername) {
		this.idstateusername = idstateusername;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Useraccount> getUseraccounts() {
		return this.useraccounts;
	}

	public void setUseraccounts(Set<Useraccount> useraccounts) {
		this.useraccounts = useraccounts;
	}

}
