/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Statecall generated by hbm2java
 */
public class Statecall implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idstatecall;
	private String statecall;
	private String description;
	private Set<Logcall> logcalls = new HashSet<Logcall>(0);

	public Statecall() {
	}

	public Statecall(long idstatecall, String statecall, String description) {
		this.idstatecall = idstatecall;
		this.statecall = statecall;
		this.description = description;
	}

	public Statecall(long idstatecall, String statecall, String description,
			Set<Logcall> logcalls) {
		this.idstatecall = idstatecall;
		this.statecall = statecall;
		this.description = description;
		this.logcalls = logcalls;
	}

	public long getIdstatecall() {
		return this.idstatecall;
	}

	public void setIdstatecall(long idstatecall) {
		this.idstatecall = idstatecall;
	}

	public String getStatecall() {
		return this.statecall;
	}

	public void setStatecall(String statecall) {
		this.statecall = statecall;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Logcall> getLogcalls() {
		return this.logcalls;
	}

	public void setLogcalls(Set<Logcall> logcalls) {
		this.logcalls = logcalls;
	}

}
