/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 30/05/2014 12:55:59 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * Systemalerts generated by hbm2java
 */
public class Systemalerts implements java.io.Serializable {

	private int idAlert;
	private String alert;
	private String dsc;
	private Date dateRegister;
	private Date attended;

	public Systemalerts() {
	}

	public Systemalerts(int idAlert, String alert, Date dateRegister,
			Date attended) {
		this.idAlert = idAlert;
		this.alert = alert;
		this.dateRegister = dateRegister;
		this.attended = attended;
	}

	public Systemalerts(int idAlert, String alert, String dsc,
			Date dateRegister, Date attended) {
		this.idAlert = idAlert;
		this.alert = alert;
		this.dsc = dsc;
		this.dateRegister = dateRegister;
		this.attended = attended;
	}

	public int getIdAlert() {
		return this.idAlert;
	}

	public void setIdAlert(int idAlert) {
		this.idAlert = idAlert;
	}

  
	public String getAlert() {
		return this.alert;
	}

	public void setAlert(String alert) {
		this.alert = alert;
	}

	public String getDsc() {
		return this.dsc;
	}

	public void setDsc(String dsc) {
		this.dsc = dsc;
	}

	public Date getDateRegister() {
		return this.dateRegister;
	}

	public void setDateRegister(Date dateRegister) {
		this.dateRegister = dateRegister;
	}

	public Date getAttended() {
		return this.attended;
	}

	public void setAttended(Date attended) {
		this.attended = attended;
	}

}
