/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * Transactionlog generated by hbm2java
 */
public class Transactionlog implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idtransactionlog;
	private Date dateserver;
	private String source;
	private String messagesource;
	private String sink;
	private String messagesink;
	private Date updateserver;

	public Transactionlog() {
	}

	public Transactionlog(long idtransactionlog, Date dateserver,
			String source, String messagesource, String sink, String messagesink) {
		this.idtransactionlog = idtransactionlog;
		this.dateserver = dateserver;
		this.source = source;
		this.messagesource = messagesource;
		this.sink = sink;
		this.messagesink = messagesink;
	}

	public long getIdtransactionlog() {
		return this.idtransactionlog;
	}

	public void setIdtransactionlog(long idtransactionlog) {
		this.idtransactionlog = idtransactionlog;
	}

	public Date getDateserver() {
		return this.dateserver;
	}

	public void setDateserver(Date dateserver) {
		this.dateserver = dateserver;
	}

	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	public String getMessagesource() {
		return this.messagesource;
	}

	public void setMessagesource(String messagesource) {
		this.messagesource = messagesource;
	}

	public String getSink() {
		return this.sink;
	}

	public void setSink(String sink) {
		this.sink = sink;
	}

	public String getMessagesink() {
		return this.messagesink;
	}

	public void setMessagesink(String messagesink) {
		this.messagesink = messagesink;
	}

	/**
	 * @return the updateserver
	 */
	public Date getUpdateserver() {
		return updateserver;
	}

	/**
	 * @param updateserver
	 *            the updateserver to set
	 */
	public void setUpdateserver(Date updateserver) {
		this.updateserver = updateserver;
	}

}
