/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Transactiontype generated by hbm2java
 */
public class Transactiontype implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idtransactiontype;
	private String transaction;
	private String description;
	private Set<Processingcode> processingcodes = new HashSet<Processingcode>(0);

	public Transactiontype() {
	}

	public Transactiontype(long idtransactiontype, String transaction) {
		this.idtransactiontype = idtransactiontype;
		this.transaction = transaction;
	}

	public Transactiontype(long idtransactiontype, String transaction,
			String description, Set<Processingcode> processingcodes) {
		this.idtransactiontype = idtransactiontype;
		this.transaction = transaction;
		this.description = description;
		this.processingcodes = processingcodes;
	}

	public long getIdtransactiontype() {
		return this.idtransactiontype;
	}

	public void setIdtransactiontype(long idtransactiontype) {
		this.idtransactiontype = idtransactiontype;
	}

	public String getTransaction() {
		return this.transaction;
	}

	public void setTransaction(String transaction) {
		this.transaction = transaction;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Processingcode> getProcessingcodes() {
		return this.processingcodes;
	}

	public void setProcessingcodes(Set<Processingcode> processingcodes) {
		this.processingcodes = processingcodes;
	}

}
