/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1
import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Transactions generated by hbm2java
 */
public class Transactions implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idtransactions;
	private Transferstate transferstate;
	private Pinsecurity pinsecurity;
	private Date dateserver;
	private long celnumsend;
	private long celnumreceive;
	private BigDecimal transferamount;
	private Set<Smsqueue> smsqueues = new HashSet<Smsqueue>(0);
	private Set<Txdetails> txdetailses = new HashSet<Txdetails>(0);
	private Date lastupdate;

	public Transactions() {
	}

	public Transactions(long idtransactions, Transferstate transferstate,
			Pinsecurity pinsecurity, Date dateserver, long celnumsend,
			long celnumreceive) {
		this.idtransactions = idtransactions;
		this.transferstate = transferstate;
		this.pinsecurity = pinsecurity;
		this.dateserver = dateserver;
		this.celnumsend = celnumsend;
		this.celnumreceive = celnumreceive;
	}

	public Transactions(long idtransactions, Transferstate transferstate,
			Pinsecurity pinsecurity, Date dateserver, long celnumsend,
			long celnumreceive, BigDecimal transferamount,
			Set<Smsqueue> smsqueues) {
		this.idtransactions = idtransactions;
		this.transferstate = transferstate;
		this.pinsecurity = pinsecurity;
		this.dateserver = dateserver;
		this.celnumsend = celnumsend;
		this.celnumreceive = celnumreceive;
		this.transferamount = transferamount;
		this.smsqueues = smsqueues;
	}

	public long getIdtransactions() {
		return this.idtransactions;
	}

	public void setIdtransactions(long idtransactions) {
		this.idtransactions = idtransactions;
	}

	public Transferstate getTransferstate() {
		return this.transferstate;
	}

	public void setTransferstate(Transferstate transferstate) {
		this.transferstate = transferstate;
	}

	public Pinsecurity getPinsecurity() {
		return this.pinsecurity;
	}

	public void setPinsecurity(Pinsecurity pinsecurity) {
		this.pinsecurity = pinsecurity;
	}

	public Date getDateserver() {
		return this.dateserver;
	}

	public void setDateserver(Date dateserver) {
		this.dateserver = dateserver;
	}

	public long getCelnumsend() {
		return this.celnumsend;
	}

	public void setCelnumsend(long celnumsend) {
		this.celnumsend = celnumsend;
	}

	public long getCelnumreceive() {
		return this.celnumreceive;
	}

	public void setCelnumreceive(long celnumreceive) {
		this.celnumreceive = celnumreceive;
	}

	public BigDecimal getTransferamount() {
		return this.transferamount;
	}

	public void setTransferamount(BigDecimal transferamount) {
		this.transferamount = transferamount;
	}

	public Set<Smsqueue> getSmsqueues() {
		return this.smsqueues;
	}

	public void setSmsqueues(Set<Smsqueue> smsqueues) {
		this.smsqueues = smsqueues;
	}

	/**
	 * @return the txdetailses
	 */
	public Set<Txdetails> getTxdetailses() {
		return txdetailses;
	}

	/**
	 * @param txdetailses
	 *            the txdetailses to set
	 */
	public void setTxdetailses(Set<Txdetails> txdetailses) {
		this.txdetailses = txdetailses;
	}

	/**
	 * @return the lastupdate
	 */
	public Date getLastupdate() {
		return lastupdate;
	}

	/**
	 * @param lastupdate
	 *            the lastupdate to set
	 */
	public void setLastupdate(Date lastupdate) {
		this.lastupdate = lastupdate;
	}

}
