/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Transferstate generated by hbm2java
 */
public class Transferstate implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idtransferstate;
	private byte state;
	private String description;
	private Set<Transactions> transactionses = new HashSet<Transactions>(0);

	public Transferstate() {
	}

	public Transferstate(int idtransferstate, byte state, String description) {
		this.idtransferstate = idtransferstate;
		this.state = state;
		this.description = description;
	}

	public Transferstate(int idtransferstate, byte state, String description,
			Set<Transactions> transactionses) {
		this.idtransferstate = idtransferstate;
		this.state = state;
		this.description = description;
		this.transactionses = transactionses;
	}

	public int getIdtransferstate() {
		return this.idtransferstate;
	}

	public void setIdtransferstate(int idtransferstate) {
		this.idtransferstate = idtransferstate;
	}

	public byte getState() {
		return this.state;
	}

	public void setState(byte state) {
		this.state = state;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Transactions> getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set<Transactions> transactionses) {
		this.transactionses = transactionses;
	}

}
