/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Typedata generated by hbm2java
 */
public class Typedata implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idtypedata;
	private String data;
	private String length;
	private String description;
	private Set<Fields> fieldses = new HashSet<Fields>(0);

	public Typedata() {
	}

	public Typedata(long idtypedata, String data, String length) {
		this.idtypedata = idtypedata;
		this.data = data;
		this.length = length;
	}

	public Typedata(long idtypedata, String data, String length,
			String description, Set<Fields> fieldses) {
		this.idtypedata = idtypedata;
		this.data = data;
		this.length = length;
		this.description = description;
		this.fieldses = fieldses;
	}

	public long getIdtypedata() {
		return this.idtypedata;
	}

	public void setIdtypedata(long idtypedata) {
		this.idtypedata = idtypedata;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public String getLength() {
		return this.length;
	}

	public void setLength(String length) {
		this.length = length;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<Fields> getFieldses() {
		return this.fieldses;
	}

	public void setFieldses(Set<Fields> fieldses) {
		this.fieldses = fieldses;
	}

}
