package com.peycash.persistence.domain;

// Generated 03-sep-2014 12:17:34 by Hibernate Tools 3.6.0

import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */

public class User implements java.io.Serializable {

	private int iduser;
	private String username;
	private String password;
	private String name;
	private String lastname;
	private Set<Roleuser> roleusers = new HashSet<Roleuser>(0);
	private short active;

	public User() {
	}

	public User(int iduser, String username, String password) {
		this.iduser = iduser;
		this.username = username;
		this.password = password;
	}

	public User(int iduser, String username, String password, String name,
			String lastname, Set<Roleuser> roleusers) {
		this.iduser = iduser;
		this.username = username;
		this.password = password;
		this.name = name;
		this.lastname = lastname;
		this.roleusers = roleusers;
	}

	public int getIduser() {
		return this.iduser;
	}

	public void setIduser(int iduser) {
		this.iduser = iduser;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public Set<Roleuser> getRoleusers() {
		return roleusers;
	}

	public void setRoleusers(Set<Roleuser> roleusers) {
		this.roleusers = roleusers;
	}

	public short getActive() {
        return this.active;
    }
    
    public void setActive(short active) {
        this.active = active;
    }

}
