/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;

/**
 * Userchangehistory generated by hbm2java
 */
public class Userchangehistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long iduserchangehistory;
	private Useraccount useraccount;
	private String useraccount_1;
	private String password;
	private Serializable datemodified;
	private String reason;

	public Userchangehistory() {
	}

	public Userchangehistory(long iduserchangehistory, Useraccount useraccount,
			String useraccount_1, String password, Serializable datemodified) {
		this.iduserchangehistory = iduserchangehistory;
		this.useraccount = useraccount;
		this.useraccount_1 = useraccount_1;
		this.password = password;
		this.datemodified = datemodified;
	}

	public Userchangehistory(long iduserchangehistory, Useraccount useraccount,
			String useraccount_1, String password, Serializable datemodified,
			String reason) {
		this.iduserchangehistory = iduserchangehistory;
		this.useraccount = useraccount;
		this.useraccount_1 = useraccount_1;
		this.password = password;
		this.datemodified = datemodified;
		this.reason = reason;
	}

	public long getIduserchangehistory() {
		return this.iduserchangehistory;
	}

	public void setIduserchangehistory(long iduserchangehistory) {
		this.iduserchangehistory = iduserchangehistory;
	}

	public Useraccount getUseraccount() {
		return this.useraccount;
	}

	public void setUseraccount(Useraccount useraccount) {
		this.useraccount = useraccount;
	}

	public String getUseraccount_1() {
		return this.useraccount_1;
	}

	public void setUseraccount_1(String useraccount_1) {
		this.useraccount_1 = useraccount_1;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Serializable getDatemodified() {
		return this.datemodified;
	}

	public void setDatemodified(Serializable datemodified) {
		this.datemodified = datemodified;
	}

	public String getReason() {
		return this.reason;
	}

	public void setReason(String reason) {
		this.reason = reason;
	}

}
