/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Useraccount generated by hbm2java
 */
public class Useraccount implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long iduseraccount;
	private Stateusername stateusername;
	private long idproject;
	private String useraccount;
	private String password;
	private String username;
	private boolean isactivied;
	private Set<Userchangehistory> userchangehistories = new HashSet<Userchangehistory>(
			0);

	public Useraccount() {
	}

	public Useraccount(long iduseraccount, Stateusername stateusername,
			long idproject, String useraccount, String password,
			String username, boolean isactivied) {
		this.iduseraccount = iduseraccount;
		this.stateusername = stateusername;
		this.idproject = idproject;
		this.useraccount = useraccount;
		this.password = password;
		this.username = username;
		this.isactivied = isactivied;
	}

	public Useraccount(long iduseraccount, Stateusername stateusername,
			long idproject, String useraccount, String password,
			String username, boolean isactivied,
			Set<Userchangehistory> userchangehistories) {
		this.iduseraccount = iduseraccount;
		this.stateusername = stateusername;
		this.idproject = idproject;
		this.useraccount = useraccount;
		this.password = password;
		this.username = username;
		this.isactivied = isactivied;
		this.userchangehistories = userchangehistories;
	}

	public long getIduseraccount() {
		return this.iduseraccount;
	}

	public void setIduseraccount(long iduseraccount) {
		this.iduseraccount = iduseraccount;
	}

	public Stateusername getStateusername() {
		return this.stateusername;
	}

	public void setStateusername(Stateusername stateusername) {
		this.stateusername = stateusername;
	}

	public long getIdproject() {
		return this.idproject;
	}

	public void setIdproject(long idproject) {
		this.idproject = idproject;
	}

	public String getUseraccount() {
		return this.useraccount;
	}

	public void setUseraccount(String useraccount) {
		this.useraccount = useraccount;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean isIsactivied() {
		return this.isactivied;
	}

	public void setIsactivied(boolean isactivied) {
		this.isactivied = isactivied;
	}

	public Set<Userchangehistory> getUserchangehistories() {
		return this.userchangehistories;
	}

	public void setUserchangehistories(
			Set<Userchangehistory> userchangehistories) {
		this.userchangehistories = userchangehistories;
	}

}
