/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

/**
 * Workerrole generated by hbm2java
 */
public class Workerrole implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idworkerrole;
	private Project project;
	private String name;
	private String description;
	private String pecomment;
	private boolean isactivied;

	public Workerrole() {
	}

	public Workerrole(long idworkerrole, Project project, String name,
			boolean isactivied) {
		this.idworkerrole = idworkerrole;
		this.project = project;
		this.name = name;
		this.isactivied = isactivied;
	}

	public Workerrole(long idworkerrole, Project project, String name,
			String description, String pecomment, boolean isactivied) {
		this.idworkerrole = idworkerrole;
		this.project = project;
		this.name = name;
		this.description = description;
		this.pecomment = pecomment;
		this.isactivied = isactivied;
	}

	public long getIdworkerrole() {
		return this.idworkerrole;
	}

	public void setIdworkerrole(long idworkerrole) {
		this.idworkerrole = idworkerrole;
	}

	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getPecomment() {
		return this.pecomment;
	}

	public void setPecomment(String pecomment) {
		this.pecomment = pecomment;
	}

	public boolean isIsactivied() {
		return this.isactivied;
	}

	public void setIsactivied(boolean isactivied) {
		this.isactivied = isactivied;
	}

}
