/*
 * Peycash 2014 - All rights reserved
 */
package com.peycash.persistence.domain;

// Generated 28/03/2014 11:10:54 AM by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * Workday generated by hbm2java
 */
public class Workday implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private long idworkday;
	private Boolean monday;
	private Boolean tuesday;
	private Boolean wednesday;
	private Boolean thursday;
	private Boolean friday;
	private Boolean saturday;
	private Boolean sunday;
	private Serializable checkin;
	private Serializable checkout;
	private Set<Pebranch> pebranches = new HashSet<Pebranch>(0);

	public Workday() {
	}

	public Workday(long idworkday) {
		this.idworkday = idworkday;
	}

	public Workday(long idworkday, Boolean monday, Boolean tuesday,
			Boolean wednesday, Boolean thursday, Boolean friday,
			Boolean saturday, Boolean sunday, Serializable checkin,
			Serializable checkout, Set<Pebranch> pebranches) {
		this.idworkday = idworkday;
		this.monday = monday;
		this.tuesday = tuesday;
		this.wednesday = wednesday;
		this.thursday = thursday;
		this.friday = friday;
		this.saturday = saturday;
		this.sunday = sunday;
		this.checkin = checkin;
		this.checkout = checkout;
		this.pebranches = pebranches;
	}

	public long getIdworkday() {
		return this.idworkday;
	}

	public void setIdworkday(long idworkday) {
		this.idworkday = idworkday;
	}

	public Boolean getMonday() {
		return this.monday;
	}

	public void setMonday(Boolean monday) {
		this.monday = monday;
	}

	public Boolean getTuesday() {
		return this.tuesday;
	}

	public void setTuesday(Boolean tuesday) {
		this.tuesday = tuesday;
	}

	public Boolean getWednesday() {
		return this.wednesday;
	}

	public void setWednesday(Boolean wednesday) {
		this.wednesday = wednesday;
	}

	public Boolean getThursday() {
		return this.thursday;
	}

	public void setThursday(Boolean thursday) {
		this.thursday = thursday;
	}

	public Boolean getFriday() {
		return this.friday;
	}

	public void setFriday(Boolean friday) {
		this.friday = friday;
	}

	public Boolean getSaturday() {
		return this.saturday;
	}

	public void setSaturday(Boolean saturday) {
		this.saturday = saturday;
	}

	public Boolean getSunday() {
		return this.sunday;
	}

	public void setSunday(Boolean sunday) {
		this.sunday = sunday;
	}

	public Serializable getCheckin() {
		return this.checkin;
	}

	public void setCheckin(Serializable checkin) {
		this.checkin = checkin;
	}

	public Serializable getCheckout() {
		return this.checkout;
	}

	public void setCheckout(Serializable checkout) {
		this.checkout = checkout;
	}

	public Set<Pebranch> getPebranches() {
		return this.pebranches;
	}

	public void setPebranches(Set<Pebranch> pebranches) {
		this.pebranches = pebranches;
	}

}
